name: Dalenberg
favicon: null
layout_spectrum: 0.70907720644027
typography_spectrum: 0.08622958231717348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8313018414191902
  lightness: 0.347529455088079
  saturation: 0.4450279250741005
  rhythmicContrast: 0.9945548963733017
purpose: []
