name: Dalenberg
favicon: null
layout_spectrum: 0.8418833389878273
typography_spectrum: 0.7397474378813058
title: Joe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#103756'
    - '#afa99d'
    - '#547268'
    - '#141609'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
