name: Dalenberg
favicon: null
layout_spectrum: 0.008017692482098937
typography_spectrum: 0.4849361190572381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.024272457463666797
  lightness: 0.4651443469338119
  saturation: 0.394268382107839
  rhythmicContrast: 0.38040107348933816
purpose: []
