name: Dalenberg
favicon: null
layout_spectrum: 0.5017164195887744
typography_spectrum: 0.8938525372650474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36234741215594113
  lightness: 0.20043344236910343
  saturation: 0.45234053931199014
  rhythmicContrast: 0.5101728171575814
purpose: []
